### PR TITLE
Use of the head of the svn webkit

### PR DESCRIPTION
**Pull request by ThierryHFR**
Add 2 correctifs found in arch linux :

1 :
==
  diff -Naur a/ewebkit/Source/WebKit2/PlatformEfl.cmake b/ewebkit/Source/WebKit2/PlatformEfl.cmake
--- a/ewebkit/Source/WebKit2/PlatformEfl.cmake  2016-08-04 15:31:20.000000000 +0200
+++ b/ewebkit/Source/WebKit2/PlatformEfl.cmake  2016-10-16 14:58:56.063561199 +0200
@@ -402,6 +402,7 @@
     "${CMAKE_CURRENT_SOURCE_DIR}/UIProcess/API/efl/ewk_url_response.h"
     "${CMAKE_CURRENT_SOURCE_DIR}/UIProcess/API/efl/ewk_url_scheme_request.h"
     "${CMAKE_CURRENT_SOURCE_DIR}/UIProcess/API/efl/ewk_view.h"
+    "${CMAKE_CURRENT_SOURCE_DIR}/UIProcess/API/efl/ewk_view_configuration.h"
     "${CMAKE_CURRENT_SOURCE_DIR}/UIProcess/API/efl/ewk_window_features.h"
 )

2 : 
==
sed -i /-Werror/d Source/cmake/WebKitHelpers.cmake

### CODE REVIEW

**Comment by Gyuyoung** [comment]
@thierryOrdissimo  Is this patch to rebase ewebkit-1.18 with WebKit latest trunk ?

**Comment by ThierryHFR** [comment]
Yes. the git version is broken: make -j1 => fails.
I try to get a html viewer EFL. My current test have failed.
the svn compiles correctly. But whatever the version, that of that of the git or svn, "ewk_view_add" failed.
My patch is not conclusive, since the test program does not work better.
I'm afraid I have wasted your time.

**Comment by Gyuyoung** [comment]
I'm going to make a new branch for ewebkit-1.19 based on latest WebKit trunk. I think it would be good if you use the new branch instead of updating the ewebkit-1.18. How do you think ?

**Comment by ThierryHFR** [comment]
I'm going to try... Thank you

**Comment by Gyuyoung** [comment]
Hi, I make an ewebkit-1.19 branch based on Nov. 11 WebKit commit. I'm going to merge ewebkit-1.18 patces into ewebkit-1.19. Please use ewebkit-1.19 branch.

**Comment by ThierryHFR** [comment]
Thank you. I just tried to compile the 1.19:

[13/3705] Building CXX object Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/SelectorPseudoClassAndCompatibilityElementMap.cpp.o
FAILED: Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/SelectorPseudoClassAndCompatibilityElementMap.cpp.o 
/usr/bin/c++     @Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/SelectorPseudoClassAndCompatibilityElementMap.cpp.o.rsp -MD -MT Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/SelectorPseudoClassAndCompatibilityElementMap.cpp.o -MF Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/SelectorPseudoClassAndCompatibilityElementMap.cpp.o.d -o Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/SelectorPseudoClassAndCompatibilityElementMap.cpp.o -c DerivedSources/WebCore/SelectorPseudoClassAndCompatibilityElementMap.cpp
In file included from SelectorPseudoClassAndCompatibilityElementMap.gperf:33:0:
../../Source/WebCore/css/parser/CSSParserValues.h: In member function ‘bool WebCore::CSSParserSelector::needsImplicitShadowCombinatorForMatching() const’:
../../Source/WebCore/css/parser/CSSParserValues.h:266:345: error: ‘PseudoElementCue’ is not a member of ‘WebCore::CSSSelector’
     bool needsImplicitShadowCombinatorForMatching() const { return match() == CSSSelector::PseudoElement && (pseudoElementType() == CSSSelector::PseudoElementWebKitCustom || pseudoElementType() == CSSSelector::PseudoElementUserAgentCustom || pseudoElementType() == CSSSelector::PseudoElementWebKitCustomLegacyPrefixed || pseudoElementType() == CSSSelector::PseudoElementCue); }
                                                                                                                                                                                                                                                                                                                                                         ^~~~~~~~~~~
[16/3705] Building CXX object Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/CSSGrammar.cpp.o
FAILED: Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/CSSGrammar.cpp.o 
/usr/bin/c++     @Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/CSSGrammar.cpp.o.rsp -MD -MT Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/CSSGrammar.cpp.o -MF Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/CSSGrammar.cpp.o.d -o Source/WebCore/CMakeFiles/WebCoreDerivedSources.dir/**/**/DerivedSources/WebCore/CSSGrammar.cpp.o -c DerivedSources/WebCore/CSSGrammar.cpp
In file included from ../../Source/WebCore/css/parser/CSSParser.h:29:0,
                 from /home/debian/ewebkit-1.19/ewebkit/WebKitBuild/Release/DerivedSources/WebCore/CSSGrammar.y:27:
../../Source/WebCore/css/parser/CSSParserValues.h: In member function ‘bool WebCore::CSSParserSelector::needsImplicitShadowCombinatorForMatching() const’:
../../Source/WebCore/css/parser/CSSParserValues.h:266:345: error: ‘PseudoElementCue’ is not a member of ‘WebCore::CSSSelector’
     bool needsImplicitShadowCombinatorForMatching() const { return match() == CSSSelector::PseudoElement && (pseudoElementType() == CSSSelector::PseudoElementWebKitCustom || pseudoElementType() == CSSSelector::PseudoElementUserAgentCustom || pseudoElementType() == CSSSelector::PseudoElementWebKitCustomLegacyPrefixed || pseudoElementType() == CSSSelector::PseudoElementCue); }
                                                                                                                                                                                                                                                                                                                                                         ^~~~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by ThierryHFR** [comment]
Ewebkit 1.18 compiles. My patch on version release 1.18 and my compilation options.
Test on Debian Stretch and Ubuntu Yakkety.

[ewebkit-release-1.18.zip](https://github.com/Gyuyoung/ewebkit/files/589499/ewebkit-release-1.18.zip)

./Tools/Scripts/build-webkit --efl --no-video --no-web-audio --no-video-track --prefix=/home/debian/ewebkit-1.19/tmp --cmakeargs="-DENABLE_MEDIA_STREAM=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_API_TESTS=OFF -DENABLE_SPEECH_SYNTHESIS=OFF -DUSE_LIBHYPHEN=OFF -DENABLE_MEDIA_SOURCE=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_INSTALL_DIR=/usr/lib -DLIBEXEC_INSTALL_DIR=/usr/lib/ewebkit" -DCMAKE_EXE_LINKER_FLAGS="-lpthread -lm"

**Comment by Gyuyoung** [comment]
@thierryOrdissimo If you have any build break on your linux box, I think it would be best to fix on WebKit master branch. Could you let me know what linux distro and version you're using ? I wanna fix the breaks on webkit mainline.

**Comment by ThierryHFR** [comment]
I have attached to the archive some files. 
My distribution is debian Stretch [Linux debian 4.7.0-1-amd64 #1 SMP Debian 4.7.6-1 (2016-10-07) x86_64 GNU/Linux].
I remain at your disposal for further information.

[ewebkit-build-1.19.zip](https://github.com/Gyuyoung/ewebkit/files/602978/ewebkit-build-1.19.zip)

**Comment by Gyuyoung** [comment]
@thierryOrdissimo  WebKit EFL can be built on Debian/Linux 8. I guess that your build breaks might be came from disabling some features. There may be build errors if some features are disabled.

**Comment by ThierryHFR** [comment]
The same file with no special options.
[ewebkit-1.9-build.zip](https://github.com/Gyuyoung/ewebkit/files/608698/ewebkit-1.9-build.zip)

**Pull request closed without merging**
